#设置端口号（80为默认访问时不需要填写端口号）
server:
  port: 80
#配置数据源
spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #关闭页面缓存
  thymeleaf:
    cache: false